# Generated by cucumber-sinatra. (2011-05-30 13:22:39 +0200)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/annuaire.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Annuaire

class AnnuaireWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  AnnuaireWorld.new
end
